name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 UTC 自动运行
  workflow_dispatch:     # 允许你手动运行

jobs:
  update-readme:
    name: Update WakaTime stats in README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Waka Readme
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
